# Working deployment pipeline to compute engine

steps:
  # Build and push app 1
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1', './nginx']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1']


  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'scp'
      - '--zone=europe-west1-b'
      - 'pull_images.sh'
      - 'gustav@test-dc3:/opt/'


  # Run docker compose 
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - '--zone=europe-west1-b'
      - 'gustav@test-dc3'
      - '--command'
      - '/opt/pull_images.sh'

timeout: 1200s
images:
  - 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1'

options:
  logging: CLOUD_LOGGING_ONLY


# gcloud secrets create cloud-build-ssh-key --replication-policy="automatic" --data-file=/home/gustav/.ssh/cloud_build_ssh_key

# gcloud secrets create cloud-build-ssh-key-pub --replication-policy="automatic" --data-file=/home/gustav/.ssh/cloud_build_ssh_key.pub

# gcloud secrets add-iam-policy-binding cloud-build-ssh-key --member="serviceAccount:317848048979@cloudbuild.gserviceaccount.com" --role="roles/secretmanager.secretAccessor"

# gcloud secrets add-iam-policy-binding cloud-build-ssh-key-pub --member="serviceAccount:317848048979@cloudbuild.gserviceaccount.com" --role="roles/secretmanager.secretAccessor"


