#cloud-config

users:
- name: cloudservice
  uid: 2000

write_files:
- path: /etc/systemd/system/cloudservice.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Start a simple docker container
    Wants=gcr-online.target
    After=gcr-online.target

    [Service]
    Environment="HOME=/home/cloudservice"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker --registries europe-west1-docker.pkg.dev
    ExecStart=/usr/bin/docker run --rm --name=mycloudservice -v /var/run/docker.sock:/var/run/docker.sock -v "$PWD:$PWD" -w="$PWD" docker/compose:1.29.2 --file '/home/cloudservice/docker-compose.yml' up -d --build
    ExecStop=/usr/bin/docker run --rm --name=mycloudservice -v /var/run/docker.sock:/var/run/docker.sock -v "$PWD:$PWD" -w="$PWD" docker/compose:1.29.2 -f '/home/cloudservice/docker-compose.yml' down

- path: /home/cloudservice/docker-compose.yml
  permissions: 0644
  owner: cloudservice
  content: |
    version: '3'
    services:
      container1:
        image: europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1
        ports:
          - "80:80"
runcmd:
- systemctl daemon-reload
- systemctl start cloudservice.service

