# Working deployment pipeline to compute engine
# Execution commands are 

steps:
  # Build and push app 1
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1', './nginx']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1']


  # Step 3: Update metadata for managed instance group
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
          echo "Hello, world!" 
          cloud_config=$(cat cloud-config-dc2.yml)          
          gcloud compute instance-groups managed all-instances-config update bcsrd-group --zone=europe-west1-b --metadata "user-data=$cloud_config"


  # Step 4: Trigger rolling update for managed instance group
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instance-groups'
      - 'managed'
      - 'rolling-action'
      - 'replace'
      - 'bcsrd-group'
      - '--max-surge=0'
      - '--max-unavailable=1'
      - '--replacement-method=recreate'
      - '--zone=europe-west1-b'

timeout: 1200s
images:
  - 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1'

options:
  logging: CLOUD_LOGGING_ONLY


# gcloud secrets create cloud-build-ssh-key --replication-policy="automatic" --data-file=/home/gustav/.ssh/cloud_build_ssh_key

# gcloud secrets create cloud-build-ssh-key-pub --replication-policy="automatic" --data-file=/home/gustav/.ssh/cloud_build_ssh_key.pub

# gcloud secrets add-iam-policy-binding cloud-build-ssh-key --member="serviceAccount:317848048979@cloudbuild.gserviceaccount.com" --role="roles/secretmanager.secretAccessor"

# gcloud secrets add-iam-policy-binding cloud-build-ssh-key-pub --member="serviceAccount:317848048979@cloudbuild.gserviceaccount.com" --role="roles/secretmanager.secretAccessor"


