# Working deployment pipeline to compute engine

steps:
  # Build and push app 1
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1', './nginx']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1']

  # Pull image to GCE instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - '--zone=europe-west1-b'
      - 'gustav@test-dc3'
      - '--command'
      - 'TOKEN=$(curl --silent --header  "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token) && ACCESS=$(echo $${TOKEN} | grep --extended-regexp --only-matching "(ya29.[0-9a-zA-Z._-]*)") && /usr/bin/docker login -u oauth2accesstoken -p "$${ACCESS}" https://europe-west1-docker.pkg.dev && /usr/bin/docker pull europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1'

  # Run docker compose 
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - '--zone=europe-west1-b'
      - 'gustav@test-dc3'
      - '--command'
      - '/usr/bin/docker run --rm -v  /var/run/docker.sock:/var/run/docker.sock -v "/home/composer/.docker:/root/.docker" -v "/home/composer:/home/composer" -w="/home/composer" docker/compose:1.24.0 up -d --build'

timeout: 1200s
images:
  - 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1'

options:
  logging: CLOUD_LOGGING_ONLY


# gcloud secrets create cloud-build-ssh-key --replication-policy="automatic" --data-file=/home/gustav/.ssh/cloud_build_ssh_key

# gcloud secrets create cloud-build-ssh-key-pub --replication-policy="automatic" --data-file=/home/gustav/.ssh/cloud_build_ssh_key.pub

# gcloud secrets add-iam-policy-binding cloud-build-ssh-key --member="serviceAccount:317848048979@cloudbuild.gserviceaccount.com" --role="roles/secretmanager.secretAccessor"

# gcloud secrets add-iam-policy-binding cloud-build-ssh-key-pub --member="serviceAccount:317848048979@cloudbuild.gserviceaccount.com" --role="roles/secretmanager.secretAccessor"


