
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'europe-west1-docker.pkg.dev/cbuild/flaskdemo:tag1'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-west1-docker.pkg.dev/cbuild/flaskdemo:tag1'
timeout: 1200s
images:
  - 'europe-west1-docker.pkg.dev/cbuild/flaskdemo:tag1'
options:
  logging: CLOUD_LOGGING_ONLY