
steps:
  # Build and push app 1
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1', './nginx']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1']

  # Build and push app 2
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'europe-west1-docker.pkg.dev/reportall/cbuild/flaskdemo:tag1'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-west1-docker.pkg.dev/reportall/cbuild/flaskdemo:tag1'
timeout: 1200s
images:
  - 'europe-west1-docker.pkg.dev/reportall/cbuild/flaskdemo:tag1'
options:
  logging: CLOUD_LOGGING_ONLY