
steps:
  # Build and push app 1
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1', './nginx']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1']
  
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['compute', 'ssh', '--zone=europe-west1-b', 'gustav@test-dc3']

  # - name: 'docker'
  #   args: ['pull', 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1']

  # - name: 'docker'
  #   args: ['pull', 'docker/compose:1.24.0']

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['compute', 'ssh', '--zone=europe-west1-b', 'gustav@test-dc3', '--command', '/usr/bin/docker run --rm -v  /var/run/docker.sock:/var/run/docker.sock -v "/home/composer/.docker:/root/.docker" -v "/home/composer:/home/composer" -w="/home/composer" docker/compose:1.24.0 up -d']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - '--zone=europe-west1-b'
      - 'gustav@test-dc3'
      - '--command'
      - '/usr/bin/docker pull europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1'


  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - '--zone=europe-west1-b'
      - 'gustav@test-dc3'
      - '--command'
      - '/usr/bin/docker run --rm -v  /var/run/docker.sock:/var/run/docker.sock -v "/home/composer/.docker:/root/.docker" -v "/home/composer:/home/composer" -w="/home/composer" docker/compose:1.24.0 up -d --build'

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   id: Connect to instance
  #   entrypoint: /bin/sh
  #   args:
  #     - '-c'
  #     - |
  #         ls -la /builder
  #         mkdir -p /builder/home/.ssh
  #         touch /builder/home/.ssh/google_compute_known_hosts
  #         chmod g+w /builder/home/.ssh/google_compute_known_hosts
  #         gcloud secrets versions access latest --secret=cloud-build-ssh-key > /builder/home/.ssh/id_rsa
  #         chmod 600 /builder/home/.ssh/id_rsa
  #         gcloud secrets versions access latest --secret=cloud-build-ssh-key-pub > /builder/home/.ssh/id_rsa.pub
  #         chmod 600 /builder/home/.ssh/id_rsa.pub
  #         set -x
  #         gcloud compute ssh test-dc3 --ssh-key-file=/builder/home/.ssh/id_rsa --zone=europe-west1-b

  # - name: 'bash'
  #   script: |
  #     #!/usr/bin/env bash
  #     echo "Hello $USER"
  #     echo "Hello $PWD"
  #     echo $(ls /home/)

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: "bash"
  #   args:
  #     - "-c"
  #     - |
  #         echo "enter 1 bash command per line"
  #         ls -la
  #         gcloud version

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: 'bash'
  #   args: ['/home/composer/auth.sh']

  # - name: 'bash'
  #   script: |
  #     #!/usr/bin/env bash
  #     echo "Hello $USER"
  #     /usr/bin/docker run --rm -v  /var/run/docker.sock:/var/run/docker.sock -v "/home/composer/.docker:/root/.docker" -v "/home/composer:/home/composer" -w="/home/composer" docker/compose:1.24.0 up

  # - name: 'docker'
  #   args: ['run', '--rm', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-v', '/home/composer/.docker:/root/.docker', '-v', '/home/composer:/home/composer', '-w', '/home/composer', 'docker/compose:1.24.0', 'up']

timeout: 1200s
images:
  - 'europe-west1-docker.pkg.dev/reportall/cbuild/nginx:tag1'

options:
  logging: CLOUD_LOGGING_ONLY


# gcloud secrets create cloud-build-ssh-key --replication-policy="automatic" --data-file=/home/gustav/.ssh/cloud_build_ssh_key

# gcloud secrets create cloud-build-ssh-key-pub --replication-policy="automatic" --data-file=/home/gustav/.ssh/cloud_build_ssh_key.pub

# gcloud secrets add-iam-policy-binding cloud-build-ssh-key --member="serviceAccount:317848048979@cloudbuild.gserviceaccount.com" --role="roles/secretmanager.secretAccessor"

# gcloud secrets add-iam-policy-binding cloud-build-ssh-key-pub --member="serviceAccount:317848048979@cloudbuild.gserviceaccount.com" --role="roles/secretmanager.secretAccessor"


